### ISSUE TITLE
Revisar Mostra black

### ISSUE THREAD

**Issue by eduardoliron** [fuzue/fuzue.github.io#11]
https://github.com/fuzue/fuzue.github.io/wiki/Project-contents

**Comment by aivuk** [comment]
We built a real time physical word cloud for the answers to the question "What makes a house a home?". The answers were received by an Arduino device connect to the mobile network. The words were dynamically exhibited in a 3d mapping with two projectors, with the words colliding with the walls and doors, in a world with an always changing gravity.

OR

    _A real-time, interactive word cloud capturing the essence of "What makes a house a home?". Responses, gathered via an Arduino device connected to the mobile network, come alive through a dynamic 3D mapping. Projected onto walls and doors by twin projectors, the words colliding in a world with always changing gravity, adding a mesmerizing dimension to the experience.


@elenavolpato please check the English version
