### ISSUE TITLE
Revisar Agreste

### ISSUE THREAD

**Issue by eduardoliron** [fuzue/fuzue.github.io#13]
https://github.com/fuzue/fuzue.github.io/wiki/Project-contents

**Comment by eduardoliron** [comment]
Text missing. The basic info for the text.

@elenavolpato , here is the link for the original project of the magazine
https://docs.google.com/document/d/1mM5dDQORHsC_bKVcBNPMC6rNFtzgAkb0WmaNfrkQZio/edit?usp=sharing

**Comment by elenavolpato** [comment]
@eduardoliron please check if it makes sense. I already updated in the wiki.

>_AGRESTE, Agrupamento de Estudos Ecêntricos (Eccentric Studies Group), is an online publication aimed at promoting, debating and disseminating experimental audiovisual production, dealing critically, theoretically and in practice with present, past and future works created in any media: from present bodies to the virtual figures of the internet._
